export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          logo_key: string | null;
          settings: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          logo_key?: string | null;
          settings?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          logo_key?: string | null;
          settings?: Json;
          created_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string;
          org_id: string;
          email: string;
          full_name: string | null;
          role: "owner" | "admin" | "author" | "viewer";
          created_at: string;
        };
        Insert: {
          id: string;
          org_id: string;
          email: string;
          full_name?: string | null;
          role?: "owner" | "admin" | "author" | "viewer";
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          email?: string;
          full_name?: string | null;
          role?: "owner" | "admin" | "author" | "viewer";
          created_at?: string;
        };
      };
      quizzes: {
        Row: {
          id: string;
          org_id: string;
          slug: string;
          title: string;
          description: string | null;
          grades: number[];
          cover_key: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          slug: string;
          title: string;
          description?: string | null;
          grades?: number[];
          cover_key?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          slug?: string;
          title?: string;
          description?: string | null;
          grades?: number[];
          cover_key?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
      };
      quiz_versions: {
        Row: {
          id: string;
          quiz_id: string;
          org_id: string;
          version: number;
          status: "draft" | "published" | "archived";
          time_limit_seconds: number | null;
          per_question_seconds: number | null;
          shuffle_questions: boolean;
          shuffle_options: boolean;
          allow_backtrack: boolean;
          show_feedback: string;
          passing_score: number | null;
          max_attempts: number;
          negative_marking: number;
          speed_bonus_enabled: boolean;
          speed_bonus_max: number;
          published_at: string | null;
          published_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          quiz_id: string;
          org_id: string;
          version: number;
          status?: "draft" | "published" | "archived";
          time_limit_seconds?: number | null;
          per_question_seconds?: number | null;
          shuffle_questions?: boolean;
          shuffle_options?: boolean;
          allow_backtrack?: boolean;
          show_feedback?: string;
          passing_score?: number | null;
          max_attempts?: number;
          negative_marking?: number;
          speed_bonus_enabled?: boolean;
          speed_bonus_max?: number;
          published_at?: string | null;
          published_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          quiz_id?: string;
          org_id?: string;
          version?: number;
          status?: "draft" | "published" | "archived";
          time_limit_seconds?: number | null;
          per_question_seconds?: number | null;
          shuffle_questions?: boolean;
          shuffle_options?: boolean;
          allow_backtrack?: boolean;
          show_feedback?: string;
          passing_score?: number | null;
          max_attempts?: number;
          negative_marking?: number;
          speed_bonus_enabled?: boolean;
          speed_bonus_max?: number;
          published_at?: string | null;
          published_by?: string | null;
          created_at?: string;
        };
      };
      questions: {
        Row: {
          id: string;
          quiz_version_id: string;
          org_id: string;
          position: number;
          kind: "mcq_single" | "true_false" | "numeric";
          content_kind: "text" | "image" | "text_image";
          stem: Json;
          stem_html: string | null;
          stem_plain: string | null;
          media_key: string | null;
          media_alt: string | null;
          media_width: number | null;
          media_height: number | null;
          media_blurhash: string | null;
          explanation: Json | null;
          explanation_html: string | null;
          points: number;
          time_seconds: number | null;
          numeric_answer: number | null;
          numeric_tolerance: number;
          numeric_unit: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          quiz_version_id: string;
          org_id: string;
          position: number;
          kind: "mcq_single" | "true_false" | "numeric";
          content_kind?: "text" | "image" | "text_image";
          stem: Json;
          stem_html?: string | null;
          stem_plain?: string | null;
          media_key?: string | null;
          media_alt?: string | null;
          media_width?: number | null;
          media_height?: number | null;
          media_blurhash?: string | null;
          explanation?: Json | null;
          explanation_html?: string | null;
          points?: number;
          time_seconds?: number | null;
          numeric_answer?: number | null;
          numeric_tolerance?: number;
          numeric_unit?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          quiz_version_id?: string;
          org_id?: string;
          position?: number;
          kind?: "mcq_single" | "true_false" | "numeric";
          content_kind?: "text" | "image" | "text_image";
          stem?: Json;
          stem_html?: string | null;
          stem_plain?: string | null;
          media_key?: string | null;
          media_alt?: string | null;
          media_width?: number | null;
          media_height?: number | null;
          media_blurhash?: string | null;
          explanation?: Json | null;
          explanation_html?: string | null;
          points?: number;
          time_seconds?: number | null;
          numeric_answer?: number | null;
          numeric_tolerance?: number;
          numeric_unit?: string | null;
          created_at?: string;
        };
      };
      question_options: {
        Row: {
          id: string;
          question_id: string;
          org_id: string;
          position: number;
          label: Json;
          label_html: string | null;
          media_key: string | null;
          media_alt: string | null;
          is_correct: boolean;
        };
        Insert: {
          id?: string;
          question_id: string;
          org_id: string;
          position: number;
          label: Json;
          label_html?: string | null;
          media_key?: string | null;
          media_alt?: string | null;
          is_correct?: boolean;
        };
        Update: {
          id?: string;
          question_id?: string;
          org_id?: string;
          position?: number;
          label?: Json;
          label_html?: string | null;
          media_key?: string | null;
          media_alt?: string | null;
          is_correct?: boolean;
        };
      };
      participants: {
        Row: {
          id: string;
          org_id: string;
          personal_id: string;
          full_name: string;
          nationality: string | null;
          date_of_birth: string | null;
          age: number | null;
          gender: "male" | "female" | "other" | "undisclosed" | null;
          grade: string | null;
          school: string | null;
          agency: string | null;
          email: string | null;
          phone: string | null;
          external_ref: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          personal_id: string;
          full_name: string;
          nationality?: string | null;
          date_of_birth?: string | null;
          age?: number | null;
          gender?: "male" | "female" | "other" | "undisclosed" | null;
          grade?: string | null;
          school?: string | null;
          agency?: string | null;
          email?: string | null;
          phone?: string | null;
          external_ref?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          personal_id?: string;
          full_name?: string;
          nationality?: string | null;
          date_of_birth?: string | null;
          age?: number | null;
          gender?: "male" | "female" | "other" | "undisclosed" | null;
          grade?: string | null;
          school?: string | null;
          agency?: string | null;
          email?: string | null;
          phone?: string | null;
          external_ref?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      session_tokens: {
        Row: {
          id: string;
          org_id: string;
          participant_id: string;
          quiz_version_id: string;
          competition_session_id: string | null;
          api_key_id: string | null;
          token_hash: string;
          token_prefix: string;
          mode: "solo" | "live";
          live_room_id: string | null;
          expires_at: string;
          not_before: string | null;
          redeemed_at: string | null;
          redeemed_ip: string | null;
          revoked_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          participant_id: string;
          quiz_version_id: string;
          competition_session_id?: string | null;
          api_key_id?: string | null;
          token_hash: string;
          token_prefix: string;
          mode?: "solo" | "live";
          live_room_id?: string | null;
          expires_at: string;
          not_before?: string | null;
          redeemed_at?: string | null;
          redeemed_ip?: string | null;
          revoked_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          participant_id?: string;
          quiz_version_id?: string;
          competition_session_id?: string | null;
          api_key_id?: string | null;
          token_hash?: string;
          token_prefix?: string;
          mode?: "solo" | "live";
          live_room_id?: string | null;
          expires_at?: string;
          not_before?: string | null;
          redeemed_at?: string | null;
          redeemed_ip?: string | null;
          revoked_at?: string | null;
          created_at?: string;
        };
      };
      quiz_sessions: {
        Row: {
          id: string;
          org_id: string;
          token_id: string;
          participant_id: string;
          quiz_version_id: string;
          mode: "solo" | "live";
          live_room_id: string | null;
          state: "issued" | "active" | "submitted" | "expired" | "abandoned" | "voided";
          question_order: string[];
          started_at: string | null;
          deadline_at: string | null;
          submitted_at: string | null;
          last_seen_at: string | null;
          duration_ms: number | null;
          raw_score: number | null;
          max_score: number | null;
          percentage: number | null;
          passed: boolean | null;
          correct_count: number | null;
          incorrect_count: number | null;
          unanswered_count: number | null;
          user_agent: string | null;
          ip_address: string | null;
          integrity_flags: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          token_id: string;
          participant_id: string;
          quiz_version_id: string;
          mode?: "solo" | "live";
          live_room_id?: string | null;
          state?: "issued" | "active" | "submitted" | "expired" | "abandoned" | "voided";
          question_order?: string[];
          started_at?: string | null;
          deadline_at?: string | null;
          submitted_at?: string | null;
          last_seen_at?: string | null;
          duration_ms?: number | null;
          raw_score?: number | null;
          max_score?: number | null;
          percentage?: number | null;
          passed?: boolean | null;
          correct_count?: number | null;
          incorrect_count?: number | null;
          unanswered_count?: number | null;
          user_agent?: string | null;
          ip_address?: string | null;
          integrity_flags?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          token_id?: string;
          participant_id?: string;
          quiz_version_id?: string;
          mode?: "solo" | "live";
          live_room_id?: string | null;
          state?: "issued" | "active" | "submitted" | "expired" | "abandoned" | "voided";
          question_order?: string[];
          started_at?: string | null;
          deadline_at?: string | null;
          submitted_at?: string | null;
          last_seen_at?: string | null;
          duration_ms?: number | null;
          raw_score?: number | null;
          max_score?: number | null;
          percentage?: number | null;
          passed?: boolean | null;
          correct_count?: number | null;
          incorrect_count?: number | null;
          unanswered_count?: number | null;
          user_agent?: string | null;
          ip_address?: string | null;
          integrity_flags?: Json;
          created_at?: string;
        };
      };
      session_answers: {
        Row: {
          id: string;
          session_id: string;
          org_id: string;
          question_id: string;
          selected_option_id: string | null;
          numeric_response: number | null;
          bool_response: boolean | null;
          is_correct: boolean | null;
          points_awarded: number;
          speed_bonus: number;
          displayed_at: string | null;
          answered_at: string | null;
          time_taken_ms: number | null;
          revision_count: number;
        };
        Insert: {
          id?: string;
          session_id: string;
          org_id: string;
          question_id: string;
          selected_option_id?: string | null;
          numeric_response?: number | null;
          bool_response?: boolean | null;
          is_correct?: boolean | null;
          points_awarded?: number;
          speed_bonus?: number;
          displayed_at?: string | null;
          answered_at?: string | null;
          time_taken_ms?: number | null;
          revision_count?: number;
        };
        Update: {
          id?: string;
          session_id?: string;
          org_id?: string;
          question_id?: string;
          selected_option_id?: string | null;
          numeric_response?: number | null;
          bool_response?: boolean | null;
          is_correct?: boolean | null;
          points_awarded?: number;
          speed_bonus?: number;
          displayed_at?: string | null;
          answered_at?: string | null;
          time_taken_ms?: number | null;
          revision_count?: number;
        };
      };
      api_keys: {
        Row: {
          id: string;
          org_id: string;
          name: string;
          key_hash: string;
          key_prefix: string;
          environment: string;
          scopes: string[];
          quiz_ids: string[] | null;
          ip_allowlist: string[] | null;
          rate_limit_rpm: number;
          last_used_at: string | null;
          expires_at: string | null;
          revoked_at: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          name: string;
          key_hash: string;
          key_prefix: string;
          environment?: string;
          scopes?: string[];
          quiz_ids?: string[] | null;
          ip_allowlist?: string[] | null;
          rate_limit_rpm?: number;
          last_used_at?: string | null;
          expires_at?: string | null;
          revoked_at?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          name?: string;
          key_hash?: string;
          key_prefix?: string;
          environment?: string;
          scopes?: string[];
          quiz_ids?: string[] | null;
          ip_allowlist?: string[] | null;
          rate_limit_rpm?: number;
          last_used_at?: string | null;
          expires_at?: string | null;
          revoked_at?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
      };
      live_rooms: {
        Row: {
          id: string;
          org_id: string;
          quiz_version_id: string;
          code: string;
          host_id: string | null;
          state: "lobby" | "question_open" | "question_locked" | "reveal" | "leaderboard" | "finished";
          current_index: number;
          settings: Json;
          started_at: string | null;
          ended_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          org_id: string;
          quiz_version_id: string;
          code: string;
          host_id?: string | null;
          state?: "lobby" | "question_open" | "question_locked" | "reveal" | "leaderboard" | "finished";
          current_index?: number;
          settings?: Json;
          started_at?: string | null;
          ended_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          org_id?: string;
          quiz_version_id?: string;
          code?: string;
          host_id?: string | null;
          state?: "lobby" | "question_open" | "question_locked" | "reveal" | "leaderboard" | "finished";
          current_index?: number;
          settings?: Json;
          started_at?: string | null;
          ended_at?: string | null;
          created_at?: string;
        };
      };
      audit_log: {
        Row: {
          id: number;
          org_id: string;
          actor_type: string;
          actor_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          diff: Json | null;
          ip_address: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          org_id: string;
          actor_type: string;
          actor_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          diff?: Json | null;
          ip_address?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          org_id?: string;
          actor_type?: string;
          actor_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          diff?: Json | null;
          ip_address?: string | null;
          created_at?: string;
        };
      };
    };
    Enums: {
      org_role: "owner" | "admin" | "author" | "viewer";
      quiz_status: "draft" | "published" | "archived";
      question_kind: "mcq_single" | "true_false" | "numeric";
      content_kind: "text" | "image" | "text_image";
      session_state: "issued" | "active" | "submitted" | "expired" | "abandoned" | "voided";
      session_mode: "solo" | "live";
      gender_kind: "male" | "female" | "other" | "undisclosed";
      room_state: "lobby" | "question_open" | "question_locked" | "reveal" | "leaderboard" | "finished";
    };
  };
};
